services:
  - type: web
    name: miningniti
    env: python
    plan: free
    runtime: python3
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-dev
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
     envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://miningniti-ap.onrender.com
